server:
  port: 8089

spring:
  datasource:
    username: satellite
    password: satellite
    url: jdbc:mysql://localhost:3306/satellite
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true